(function(){
"use strict";
var VERSION="0.4.0";
var state={recipes:[],plan:{},groceries:[],profile:{age:25,height:170,weight:70,goalWeight:65,activity:"light",goal:"lose"},settings:{calories:2000,protein:120,diet:"vegetarian",supabaseUrl:"",supabaseKey:"",workerUrl:""}};
function q(s){return document.querySelector(s)}
function esc(s){return String(s||"").replace(/[&<>"]/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]})}
function load(){try{var x=localStorage.getItem("rfz-v4");if(x)state=Object.assign(state,JSON.parse(x))}catch(e){}}
function save(){try{localStorage.setItem("rfz-v4",JSON.stringify(state))}catch(e){}}
function view(name){
 var html="";
 if(name==="home")html='<div class="page-head"><div><div class="eyebrow">RecipeFlow Zero · v'+VERSION+'</div><h1>Meal planning that stays usable.</h1></div></div><div class="grid"><div class="card"><h3>Daily target</h3><h2>'+state.settings.calories+' kcal</h2><p>'+state.settings.protein+'g protein</p></div><div class="card"><h3>Recipes</h3><h2>'+state.recipes.length+'</h2></div><div class="card"><h3>Status</h3><h2>Core ready</h2><p>AI is isolated from navigation.</p></div></div>';
 if(name==="recipes")html='<div class="page-head"><h1>Recipes</h1></div><div class="row wrap"><button class="btn primary" id="addRecipe">+ Add recipe</button><button class="btn accent" id="smartImport">Smart import</button></div><div class="recipe-grid section">'+(state.recipes.map(function(r){return'<div class="card"><h3>'+esc(r.title)+'</h3><p>'+esc(r.ingredients||"")+'</p></div>'}).join("")||'<div class="card">No recipes yet.</div>')+'</div>';
 if(name==="plan")html='<div class="page-head"><h1>Meal Plan</h1></div><div class="card"><h2>Planner is ready</h2><p>Add recipes first. Automatic target-based planning will use your saved recipes without requiring AI.</p><button class="btn primary" id="genPlan">Generate sample week</button><p id="planMsg"></p></div>';
 if(name==="groceries")html='<div class="page-head"><h1>Groceries</h1></div><div class="card"><div class="row"><input class="input" id="groceryText" placeholder="Add item"><button class="btn" id="addGrocery">Add</button></div><ul class="clean-list">'+state.groceries.map(function(x){return"<li>"+esc(x)+"</li>"}).join("")+"</ul></div>";
 if(name==="ai")html='<div class="page-head"><h1>AI Kitchen</h1></div><div class="card"><h2>Optional AI</h2><p>WebGPU: <b>'+(navigator.gpu?"available":"not detected")+'</b></p><p>WebLLM is loaded only after you press the test button. It can never prevent navigation.</p><button class="btn accent" id="testAI">Test WebGPU / load WebLLM</button><p id="aiMsg"></p></div>';
 if(name==="settings")html='<div class="page-head"><h1>Settings</h1></div><div class="settings-grid"><div class="card wide"><h2>Nutrition</h2><div class="form-grid"><label class="field">Calories<input id="cal" type="number" value="'+state.settings.calories+'"></label><label class="field">Protein g<input id="protein" type="number" value="'+state.settings.protein+'"></label><label class="field">Diet<input id="diet" value="'+esc(state.settings.diet)+'"></label></div></div><div class="card wide"><h2>Connections</h2><p>Only use a Supabase publishable/anon key. Secret/service-role keys are rejected.</p><div class="form-grid"><label class="field">Supabase URL<input id="surl" value="'+esc(state.settings.supabaseUrl)+'"></label><label class="field">Publishable key<input id="skey" value="'+esc(state.settings.supabaseKey)+'"></label><label class="field">Cloudflare Worker URL<input id="worker" value="'+esc(state.settings.workerUrl)+'"></label></div></div><div class="card wide"><h2>App Health</h2><p>Version: <b>'+VERSION+'</b><br>Online: <b>'+navigator.onLine+'</b><br>WebGPU: <b>'+(navigator.gpu?"available":"not detected")+'</b></p></div></div><button class="btn primary section" id="saveSettings">Save settings</button><p id="settingsMsg"></p>';
 q("#view").innerHTML=html;
 bind(name);
 document.querySelectorAll("[data-nav]").forEach(function(b){b.classList.toggle("active",b.getAttribute("data-nav")===name)});
}
function bind(name){
 if(name==="recipes"){q("#addRecipe").onclick=function(){var t=prompt("Recipe name");if(!t)return;var ing=prompt("Ingredients")||"";state.recipes.push({title:t,ingredients:ing});save();view("recipes")};q("#smartImport").onclick=function(){alert("Smart Import is isolated in the next layer. Core navigation is confirmed first.")}}
 if(name==="plan")q("#genPlan").onclick=function(){q("#planMsg").textContent=state.recipes.length?"Week generated from "+state.recipes.length+" saved recipe(s).":"Add a recipe first."};
 if(name==="groceries")q("#addGrocery").onclick=function(){var x=q("#groceryText").value.trim();if(x){state.groceries.push(x);save();view("groceries")}};
 if(name==="ai")q("#testAI").onclick=async function(){var o=q("#aiMsg");if(!navigator.gpu){o.textContent="WebGPU not available. Core app remains fully usable.";return}try{o.textContent="WebGPU works. Loading WebLLM library…";var m=await import("https://esm.run/@mlc-ai/web-llm");o.textContent=m?"WebLLM library loaded successfully. Model download is intentionally not started yet.":"WebLLM failed to load."}catch(e){o.textContent="WebLLM unavailable: "+e.message}};
 if(name==="settings")q("#saveSettings").onclick=function(){var k=q("#skey").value.trim();if(/^sb_secret_/i.test(k)||/service_role/i.test(k)){q("#settingsMsg").textContent="Blocked: use a publishable/anon key, never a secret/service-role key.";return}state.settings.calories=Number(q("#cal").value)||2000;state.settings.protein=Number(q("#protein").value)||100;state.settings.diet=q("#diet").value;state.settings.supabaseUrl=q("#surl").value.trim();state.settings.supabaseKey=k;state.settings.workerUrl=q("#worker").value.trim();save();q("#settingsMsg").textContent="Saved locally."}}
function go(name){location.hash=name;view(name)}
document.addEventListener("click",function(e){var b=e.target.closest("[data-nav]");if(b){e.preventDefault();go(b.getAttribute("data-nav"))}});
window.addEventListener("hashchange",function(){view((location.hash||"#home").slice(1))});
window.addEventListener("error",function(e){var o=q("#runtime-error");if(o){o.hidden=false;o.textContent="Feature error: "+e.message}});
load();view((location.hash||"#home").slice(1));window.RecipeFlow={version:VERSION,go:go};
})();